name: Build LaTeX & Update Preview

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.tex'
      - '.github/workflows/latex.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Compile LaTeX
      - name: Compile PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          # latexmk_use_xelatex: true
          # latexmk_use_lualatex: true

      - name: Rename PDF with compile date
        run: |
          ts="$(date -u '+%m%d%y')"
          mkdir -p assets
          mv resume.pdf "assets/bachtran_resume_${ts}.pdf"
          # keep a stable name for README links (optional but handy)
          cp "assets/bachtran_resume_${ts}.pdf" "assets/bachtran_resume.pdf"
          echo "RENAMED_PDF=assets/bachtran_resume_${ts}.pdf" >> $GITHUB_ENV

      - name: Generate PNG preview
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          # Use the renamed file as input, emit assets/preview.png
          pdftoppm -png -singlefile -f 1 -l 1 "${RENAMED_PDF}" assets/preview

      # Commit preview + PDFs back to repo
      - name: Commit artifacts
        if: github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: "${{ env.RENAMED_PDF }} assets/preview.png assets/bachtran_resume.pdf"
          message: "chore(ci): update resume PDF(s) & preview [skip ci]"
          default_author: github_actions
